import importlib.util
import sys
import unittest
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
GENERATOR = ROOT / "scripts" / "generate_zvvnmod.py"
NAMES = ROOT / "data" / "zvvnmod-unicode-names.csv"


def load_generator():
    spec = importlib.util.spec_from_file_location("generate_zvvnmod", GENERATOR)
    module = importlib.util.module_from_spec(spec)
    assert spec.loader is not None
    sys.modules[spec.name] = module
    spec.loader.exec_module(module)
    return module


class ShapeNamingTests(unittest.TestCase):
    def test_single_shape_uses_expanded_position(self):
        gen = load_generator()
        parsed = gen.parse_shape_name("A i")
        self.assertEqual(parsed.rust_name, "A_INIT")
        self.assertEqual(parsed.units, ("A",))
        self.assertEqual(parsed.position, "Init")

    def test_init_to_fina_multi_shape_becomes_isol(self):
        gen = load_generator()
        parsed = gen.parse_shape_name("B i I f")
        self.assertEqual(parsed.rust_name, "B_I_ISOL")
        self.assertEqual(parsed.units, ("B", "I"))
        self.assertEqual(parsed.position, "Isol")

    def test_fina_to_fina_multi_code_becomes_fina(self):
        gen = load_generator()
        parsed = gen.parse_shape_name("N f Aa f")
        self.assertEqual(parsed.rust_name, "N_AA_FINA")
        self.assertEqual(parsed.units, ("N", "Aa"))
        self.assertEqual(parsed.position, "Fina")

    def test_multi_shape_position_uses_both_edges(self):
        gen = load_generator()
        self.assertEqual(gen.parse_shape_name("B i I f").rust_name, "B_I_ISOL")
        self.assertEqual(gen.parse_shape_name("B i I m").rust_name, "B_I_INIT")
        self.assertEqual(gen.parse_shape_name("B m I m").rust_name, "B_I_MEDI")
        self.assertEqual(gen.parse_shape_name("B m I f").rust_name, "B_I_FINA")
        self.assertEqual(gen.parse_shape_name("G i O m I m").rust_name, "G_O_I_INIT")

    def test_multi_shape_rejects_invalid_position_sequence(self):
        gen = load_generator()
        with self.assertRaisesRegex(ValueError, "invalid multi-shape positions"):
            gen.parse_shape_name("B f I m")

    def test_control_name_is_derived_from_csv_row(self):
        gen = load_generator()
        fvs = gen.parse_shape_name("Fvs1", codepoint=0xE140, source="control-table")
        custom = gen.parse_shape_name("Joiner", codepoint=0xE200, source="control-table")
        self.assertEqual(fvs.rust_name, "FVS1")
        self.assertEqual(custom.rust_name, "JOINER")
        self.assertTrue(fvs.is_control)
        self.assertTrue(custom.is_control)

    def test_control_table_row_requires_a_name(self):
        gen = load_generator()
        with self.assertRaisesRegex(ValueError, "missing control name"):
            gen.parse_shape_name("", codepoint=0xE140, source="control-table")

    def test_duplicate_shapes_keep_all_codes_and_first_is_canonical(self):
        gen = load_generator()
        rows = [
            gen.InputRow(0xE07F, "B i I m", "font"),
            gen.InputRow(0xE080, "B i I m", "font"),
        ]
        model = gen.build_model(rows)
        aliases = model.shape_to_codes["B_I_INIT"]
        self.assertEqual([item.codepoint for item in aliases], [0xE07F, 0xE080])
        self.assertEqual(aliases[0].const_name, "B_I_INIT")
        self.assertEqual(aliases[1].const_name, "B_I_INIT_ALT_1")

    def test_code_generator_contains_names_but_not_maps(self):
        gen = load_generator()
        rows = [
            gen.InputRow(0xE000, "A i", "font"),
            gen.InputRow(0xE07F, "B i I m", "font"),
            gen.InputRow(0xE080, "B i I m", "font"),
            gen.InputRow(0xE140, "Fvs1", "control-table"),
        ]
        output = gen.render_codes_rust(gen.build_model(rows), source_name="fixture.csv")
        self.assertIn("pub const A_INIT: ZvvnmodCode", output)
        self.assertIn("pub const B_I_INIT_ALT_1: ZvvnmodCode", output)
        self.assertIn("pub enum ZvvnmodShape", output)
        self.assertIn("pub const FVS1: ZvvnmodCode", output)
        self.assertIn("Generated by scripts/generate_zvvnmod_codes.py", output)
        self.assertNotIn("自动生成", output)
        self.assertNotIn("编码值", output)
        self.assertNotIn("CODE_TO_SHAPE", output)

    def test_map_generator_contains_bidirectional_maps(self):
        gen = load_generator()
        rows = [
            gen.InputRow(0xE000, "A i", "font"),
            gen.InputRow(0xE07F, "B i I m", "font"),
            gen.InputRow(0xE080, "B i I m", "font"),
        ]
        output = gen.render_shape_map_rust(gen.build_model(rows), source_name="fixture.csv")
        self.assertIn("use super::zvvnmod_codes::*;", output)
        self.assertIn("pub static CODE_TO_SHAPE", output)
        self.assertIn("pub fn shape_to_zvvnmod_map()", output)
        self.assertIn("B_I_INIT_ALT_1", output)
        self.assertIn("Every named glyph code", output)
        self.assertNotIn("所有具名", output)

    def test_chachleg_rows_use_final_components(self):
        gen = load_generator()
        rows = gen.read_csv(NAMES)
        by_codepoint = {row.codepoint: row for row in rows}
        self.assertEqual(by_codepoint[0xE077].name, "N f Aa f")
        self.assertEqual(by_codepoint[0xE09D].name, "Gx f Aa f")

        model = gen.build_model(rows)
        self.assertEqual(model.shape_to_codes["N_AA_FINA"][0].codepoint, 0xE077)
        self.assertEqual(model.shape_to_codes["GX_AA_FINA"][0].codepoint, 0xE09D)


if __name__ == "__main__":
    unittest.main()
